version: '3.8'
services:
  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    environment:
      - SPLUNK_GENERAL_TERMS=--accept-sgt-current-at-splunk-com
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=changeme
    ports:
      - "8000:8000"   # Web UI
      - "8088:8088"   # HTTP API
      - "8089:8089"   # HTTPS Management port
      - "9997:9997"   # Receiving port
    volumes:
      - splunk-data:/opt/splunk/var
volumes:
  splunk-data: